// <auto-generated />
using System;
using DrozdovLaw.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrozdovLaw.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrozdovLaw.Models.BlockStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_BlockStyles_Name");

                    b.ToTable("BlockStyles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Заголовок 1-го уровня",
                            Name = "h1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Заголовок 2-го уровня",
                            Name = "h2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Заголовок 3-го уровня",
                            Name = "h3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Заголовок 4-го уровня",
                            Name = "h4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Заголовок 5-го уровня",
                            Name = "h5"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Обычный абзац",
                            Name = "p"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Крупный абзац",
                            Name = "p-large"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Цитата",
                            Name = "blockquote"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Мелкий текст / сноска",
                            Name = "small"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Маркированный список (через |)",
                            Name = "ul"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Нумерованный список (через |)",
                            Name = "ol"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Номер дела",
                            Name = "e-id"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Тип результата",
                            Name = "e-details__type"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Локация / юрисдикция",
                            Name = "e-details__loc"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Определение / тип дела",
                            Name = "e-details__def"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Заголовок пояснения",
                            Name = "note-title"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Текст пояснения",
                            Name = "note-text"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Хлебные крошки (через /)",
                            Name = "breadcrumb"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Заголовок секции",
                            Name = "section-title"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Цветные точки (цвета через ,)",
                            Name = "e-dots"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Адвокат",
                            Name = "person"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Заголовок 'Решение'",
                            Name = "decision-title"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Текст решения",
                            Name = "decision-text"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Ссылка на дело",
                            Name = "case-link"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Заголовок 'Документы по делу'",
                            Name = "docs-title"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Документ PDF",
                            Name = "doc-item"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Заголовок 'Теги'",
                            Name = "tags-title"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Тег",
                            Name = "tag"
                        });
                });

            modelBuilder.Entity("DrozdovLaw.Models.ContentBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraAttribute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("StyleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("StyleId");

                    b.HasIndex("PageId", "Order")
                        .HasDatabaseName("IX_ContentBlocks_PageId_Order");

                    b.ToTable("ContentBlocks");
                });

            modelBuilder.Entity("DrozdovLaw.Models.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Code");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Code = "ru",
                            Name = "Русский"
                        },
                        new
                        {
                            Code = "en",
                            Name = "English"
                        });
                });

            modelBuilder.Entity("DrozdovLaw.Models.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("SectionId");

                    b.HasIndex("SystemName", "LanguageCode", "SectionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Pages_SystemName_LanguageCode_SectionId")
                        .HasFilter("[SectionId] IS NOT NULL");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LanguageCode = "ru",
                            Name = "Кейсы",
                            SystemName = "case"
                        },
                        new
                        {
                            Id = 2,
                            LanguageCode = "en",
                            Name = "Cases",
                            SystemName = "case"
                        });
                });

            modelBuilder.Entity("DrozdovLaw.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlagImage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StatusColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_Sections_Slug");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("DrozdovLaw.Models.ContentBlock", b =>
                {
                    b.HasOne("DrozdovLaw.Models.Page", "Page")
                        .WithMany("ContentBlocks")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrozdovLaw.Models.BlockStyle", "Style")
                        .WithMany("ContentBlocks")
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("DrozdovLaw.Models.Page", b =>
                {
                    b.HasOne("DrozdovLaw.Models.Language", "Language")
                        .WithMany("Pages")
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrozdovLaw.Models.Section", "Section")
                        .WithMany("Pages")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Language");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("DrozdovLaw.Models.BlockStyle", b =>
                {
                    b.Navigation("ContentBlocks");
                });

            modelBuilder.Entity("DrozdovLaw.Models.Language", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("DrozdovLaw.Models.Page", b =>
                {
                    b.Navigation("ContentBlocks");
                });

            modelBuilder.Entity("DrozdovLaw.Models.Section", b =>
                {
                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
